### ISSUE TITLE
:trollface: 

### ISSUE THREAD

**Issue by Void48** [tommyxchow/frosty-swiftui#4]
any plans on reviving this project and trying to fix the issues?

**Comment by tommyxchow** [comment]
Sadly, no plans 😢. Perhaps when SwiftUI matures and improves its layout system (in a year or two hopefully?), but still then very unlikely. It just didn't make sense for me to continue when in Flutter the issues were either solved instantly or in a couple of lines of code.

I figured I'd just leave the project out to the public in case anyone else wanted to give it a go and didn't mind going through through the messy parts of the code.

**Comment by Void48** [comment]
> Sadly, no plans 😢. Perhaps when SwiftUI matures and improves its layout system (in a year or two hopefully?), but still then very unlikely. It just didn't make sense for me to continue when in Flutter the issues were either solved instantly or in a couple of lines of code.
> 
> I figured I'd just leave the project out to the public in case anyone else wanted to give it a go and didn't mind going through through the messy parts of the code.

You should add topics to this repo and also maybe change the name to something more easily discoverable 👍🏻
